# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=225, null=True)),
                ('username', models.CharField(max_length=225)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('picture', models.CharField(max_length=225)),
                ('full_name', models.CharField(max_length=225)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
