# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo_leagues', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_model',
            new_name='UserModel',
        ),
    ]
